# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ddba4011b96057964fcb3d734ea6922fd312b68ff8f31c2885968f09977cc8b4b8240dfad0ad26e7898e90589afe40b3ba6922f5f6566c1a183b64162e3c00

test:
  secret_key_base: 7e167ec2ce7cc3d1f5639889484af00bc4183b33ec5246ca1f6b69c632a7413544b78f3aedaf540430bbb4e21c2c742847577925cc0f81471ff2bbac96a75822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
